default: &default
  adapter: postgresql
  pool: <%= ENV["DATABASE_POOL"] || 64 %>
  timeout: 5000
  encoding: utf-8
  user: admin
  username: admin
  password: 88888888
  port: 5432

development:
  <<: *default
  database: ddns_rails

test:
  <<: *default
  database: ddns_rails_test

production:
  <<: *default
  database: ddns_rails
